### ISSUE TITLE
How to build?

### ISSUE THREAD

**Issue by HippocampusGirl** [ohbm/hackathon_proceedings_templates#3]
We are almost ready to submit our summary, but I cannot manage to build the template without errors. I am using this command:

```bash
; latexmk \
    -bibtex \
    -pdf \
    main.tex
```

I get this error:
```
This is pdfTeX, Version 3.141592653-2.6-1.40.24 (TeX Live 2022/Arch Linux) (preloaded format=pdflatex)

...

! Package biblatex Error: \chapter not provided by class.

See the biblatex package documentation for explanation.
Type  H <return>  for immediate help.
 ...

l.80 \begin{document}

? H
The document class does not seems to support chapters.
```

A PDF is generated, but it is missing the bibliography.

Do you have any advice for how to build?

**Comment by smoia** [comment]
Hey @HippocampusGirl !
I normally build with the combo `pdflatex` + `biber` + `pdflatex`, like the [GitHub action](https://github.com/ohbm/hackathon_proceedings_templates/blob/main/.github/workflows/build-publish.yml) should be doing. Can you try like that?

**Comment by smoia** [comment]
It's also weird that you get a `chapter` error, as I didn't see any chapter mark in your PR!

**Comment by HippocampusGirl** [comment]
That's a good pointer, with the commands from the GitHub Action a PDF is generated: [main.pdf](https://github.com/ohbm/hackathon_proceedings_templates/files/9121804/main.pdf)

```bash
; mkdir -p out
; pdflatex -interaction=nonstopmode -output-directory=./out -shell-escape main.tex
; biber --input-directory=./out --output-directory=./out main
; pdflatex -interaction=nonstopmode -output-directory=./out -shell-escape main.tex
; pdflatex -interaction=nonstopmode -output-directory=./out -shell-escape main.tex
```

Minor problems:
- Somehow the bibliography is the same for each section.
- Our formulas are hard to read with the two-column format (see page 3). Do you have any recommendation for dealing with that?

**Comment by smoia** [comment]
I can fix the first problem (I just needed some files to see it through), as for the second I actually don't know what the final pagination will look like _yet_. How horrible are them?

**Comment by HippocampusGirl** [comment]
This is what it looks like now:
![image](https://user-images.githubusercontent.com/789054/179257686-d15228c7-8933-4124-9b5d-5c84c9754475.png)

I think it can be fixed by adding some more line breaks in the formula, so it’s not a big deal.

It could also be fixed by switching to a one column layout, but I don’t know if that would be too big a change at this stage.

**Comment by smoia** [comment]
I think it's safer to go for a break in the formula. I'll change it if the layout changes!

**Comment by HippocampusGirl** [comment]
Awesome! It's fixed in the pull request now
